apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    protocol={{ .Values.protocol }}
    use={{ .Values.use }}
    web={{ .Values.web }}
    server={{ .Values.server }}
    login={{ .Values.login }}
    password={{ .Values.password }}
    {{ .Values.host }}